spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:localhost}:5432/shop?reWriteBatchedInserts=true
    username: portfolio_user
    password: ${RDS_PASSWORD:portfolio1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 32

  sql:
    init:
      mode: never

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
#        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
#    org.springframework: info
    org.hibernate.stat: DEBUG

jwt:
  secret: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret-your-256-bit-secret
  token-validity-in-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,prometheus"
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    connection-timeout: 120000
  servlet:
    session:
      timeout: 120s